#!/usr/bin/python3 -cimport os, sys; os.execv(os.path.dirname(sys.argv[1]) + "/common/pywrap", sys.argv)
# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2026 Red Hat, Inc.

import testlib


@testlib.nondestructive
class TestSystemRoles(testlib.MachineCase):

    def testBasic(self) -> None:
        b = self.browser

        self.login_and_go("/system-roles")

        b.wait_in_text("body", "Manage your system with Ansible and System Roles")


if __name__ == '__main__':
    testlib.test_main()
